parameters:

    env(EXPIRATION_TIME): "1 hour"
    env(PASSWORD_STRENGTH): "4"

    private_key: "%env(PRIVATE_KEY)%"
    public_key: "%env(PUBLIC_KEY)%"

    expiration_time: "%env(EXPIRATION_TIME)%"
    password_strength: "%env(int:PASSWORD_STRENGTH)%"