apiVersion: v1
appVersion: V1.0
description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
name: uc
version: 0.1.0
home: uc.zaakonline.nl
icon: uc.zaakonline.nl