apiVersion: v1
entries:
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2020-12-23T07:35:55.7388475Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
  uc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-23T07:35:55.7031003Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 34941fc6c5ad0a3f90e41ba545511d42c79fb7b5692f089fb2757ecf1e68bb26
    home: uc.zaakonline.nl
    icon: uc.zaakonline.nl
    name: uc
    urls:
    - uc-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-23T07:35:55.6566065Z"
