apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-06-23T09:34:29.166784Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
  user-component:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-06-23T09:34:29.1565221Z"
    description: Het User Component voert het beheer over een gebruikersaccount en
      hun autorisaties. Hierbij kan in de traditionele zin worden gedacht aan aan
      een gebruiker die behoort tot bepaalde groepen die op hun beurt weer beschikken
      over bepaalde rechten. Waarbij het component tevens het bijhouden en valideren
      van wachtwoorden ondersteund (ten einde inlog mogelijkheden op bijvoorbeeld
      een dashboard of om een applicatie te faciliteren) maar in de wat abstracte
      context ondersteund het ook algemene inlogs systematieken.
    digest: ea818f5b3d82615af9c0c85ec4eadcb8b7a9f0051f27f1e2ccdf42d7d080005e
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: user-component
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - user-component-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-23T09:34:29.1513306Z"
