apiVersion: v1
entries:
  uc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-11T11:35:47.818522935Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: fa3fa7ea5e267de1085ca9f226f6207ae7a6e4a76afebd1f856b373c05b5db27
    home: uc.zaakonline.nl
    icon: uc.zaakonline.nl
    name: uc
    urls:
    - uc-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-11T11:35:47.813138035Z"
