# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
replicaCount: 2
nameOverride: ""
fullnameOverride: ""

config:
  version: V2.0
  debug: 0
  cache: true
  internal: false
  env: prod
  trustedHosts: "^.+$"
  corsAllowOrigin: [ "*" ]
  trustedProxies:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
  expirationTime: 900
  passwordStrength: 4

security:
  applicationKey: "45c1a4b6-59d3-4a6e-86bf-88a872f35845"
  secret: ""
  publicKey: ""
  privateKey: ""
  jwt:
    id:
    privateKey:
  dependencies: {}

php:
  repository: docker.io/conduction/protocomponent-php
  image: ghcr.io/conductionnl/user-component-php
  tag: latest
  env: prod
  pullPolicy: Always
  resources: {}
    # As per helm best practise, we do not enable these values by default,
    # although we do provide optimal values in the lines below that can be uncommented
    #    limits:
    #      cpu: 400m
    #      memory: 512Mi
    #    requests:
    #      cpu: 200m
    #      memory: 256Mi

nginx:
    repository: docker.io/conduction/protocomponent-nginx
    image: ghcr.io/conductionnl/user-component-nginx
    tag: latest
    pullPolicy: Always
    resources: {}
    # As per helm best practise, we do not enable these values by default,
    # although we do provide optimal values in the lines below that can be uncommented
    #    limits:
    #      cpu: 400m
    #      memory: 512Mi
    #    requests:
    #      cpu: 200m
    #      memory: 256Mi

redis:
    enabled: false
    architecture: standalone
    redisPort: 6379
    auth:
        enabled: false
    pullPolicy: IfNotPresent

postgresql:
  enabled: true
  imageTag: 10-alpine
  # If bringing your own PostgreSQL, the full uri to use
  url: "psql://a:b@example.com/c"
  postgresqlUsername: "example"
  postgresqlPassword: "!ChangeMe!"
  postgresqlDatabase: "api"
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: true
  pullPolicy: IfNotPresent
  tls:
      enabled: false
      autoGenerated: false
  volumePermissions:
      enabled: true

ingress:
    enabled: false
    className: "nginx"
    hostname: waardepapieren-service.local
    path: /
    pathType: ImplementationSpecific
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  
podAnnotations: {}

podSecurityContext: {}


securityContext:
    privileged: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    runAsNonRoot: false
#  runAsUser: 1000

autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

fixtures: {}

service:
    type: ClusterIP
    annotations: {}
    port: 80
