apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  app-version: {{ .Values.config.version | quote }}
  app-corsAllowOrigin: {{ .Values.config.corsAllowOrigin | quote }}
  cache: {{ .Values.config.cache | quote }}
  debug: {{ .Values.config.debug | quote }}
  trusted-proxies: {{ join "," .Values.config.trustedProxies }}
  trusted-hosts: {{ .Values.config.trustedHosts | quote }}
  url: {{ printf "https://%s%s" .Values.ingress.hostname .Values.ingress.path | quote }}
  {{- if .Values.redis.enabled }}
  redis-host: {{ printf "%s-headless" include "redis.fullname" . | quote }}
  redis-port: {{ .Values.redis.redisPort | toString | quote }}
  {{- end }}
  {{- if .Values.config.expirationTime }}
  expiration-time: {{ .Values.config.expirationTime | quote }}
  {{- end }}
  {{- if .Values.config.passwordStrength }}
  password-strength: {{ .Values.config.passwordStrength | quote }}
  {{- end }}
  validate-current-password: {{ .Values.config.validateCurrentPassword | quote }}
