apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "template.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "template.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: dependencies
          secret:
            secretName: {{ .Chart.Name }}-dependencies
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}-php
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.repository }}:{{ .Values.php.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /srv/api/config/packages/dependencies.yaml
              subPath: dependencies.yaml
              name: dependencies
              readOnly: true
          env:
            - name: JWT_SECRET_KEY
              value: '%kernel.project_dir%/config/jwt/private.pem'
            - name: JWT_PUBLIC_KEY
              value: '%kernel.project_dir%/config/jwt/public.pem'
            - name: JWT_PASSPHRASE
              value: 'bafe1dc254b45471754c221081f874aa'
            - name: APP_ENV
              value: {{ .Values.config.env }}
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: trusted-hosts
                  name: {{ include "template.fullname" . }}
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  key: trusted-proxies
                  name: {{ include "template.fullname" . }}
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: app-version
                  name: {{ include "template.fullname" . }}
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: {{ include "template.fullname" . }}
            - name: APP_CACHE
              valueFrom:
                configMapKeyRef:
                  key: cache
                  name: {{ include "template.fullname" . }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: {{ include "template.fullname" . }}
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                configMapKeyRef:
                  key: app-corsAllowOrigin
                  name: {{ include "template.fullname" . }}
            - name: APP_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  key: app_application_key
                  name: {{ include "template.fullname" . }}
            {{ if .Values.redis.enabled }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: redis-host
                  name: {{ include "template.fullname" . }}
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: redis-port
                  name: {{ include "template.fullname" . }}
            {{- end }}
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ include "template.fullname" . }}
            - name: PUBLIC_KEY
              valueFrom:
                  secretKeyRef:
                      key: public_key
                      name: {{ include "template.fullname" . }}
            - name: PRIVATE_KEY
              valueFrom:
                  secretKeyRef:
                      key: private_key
                      name: {{ include "template.fullname" . }}
            {{- if .Values.config.expirationTime }}
            - name: EXPIRATION_TIME
              valueFrom:
                  configMapKeyRef:
                      key: expiration-time
                      name: {{ include "template.fullname" . }}
            {{- end }}
            {{- if .Values.config.expirationTime }}
            - name: PASSWORD_STRENGTH
              valueFrom:
                  configMapKeyRef:
                      key: password-strength
                      name: {{ include "template.fullname" . }}
            {{- end }}
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-nginx
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          env:
            - name: PHP_SERVICE
              value: localhost
            - name: NGINX_HOST
              value: localhost
            - name: BACKENDS
              value: localhost
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
