apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=10" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else if .Values.postgresql.url  }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ else }}
  database-url:
  {{ end }}
  app_application_key: {{ .Values.security.applicationKey | b64enc | quote }}

  private_key: {{ .Values.security.privateKey | b64enc | quote }}
  public_key: {{ .Values.security.publicKey | b64enc | quote }}
