{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=10" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ end }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.php.mercure.jwtSecret | b64enc | quote }}
  app_commonground_id: {{ .Values.security.commongroundId | b64enc | quote }}
  app_commonground_key: {{ .Values.security.commongroundKey | b64enc | quote }}
  app_application_key: {{ .Values.security.applicationKey | b64enc | quote }}
  app_user_key: {{ .Values.security.userKey | b64enc | quote }}
  auth_provider_user: {{ .Values.security.authorisationProviderUser | b64enc | quote }}
  auth_provider_application: {{ .Values.security.authorisationProviderApplication | b64enc | quote }}
  # UC Specific secrets
  facebook_id: {{ .Values.security.facebookId | b64enc | quote }}
  facebook_secret: {{ .Values.security.facebookSecret | b64enc | quote }}
  gmail_id: {{ .Values.security.gmailId | b64enc | quote }}
  gmail_secret: {{ .Values.security.gmailSecret | b64enc | quote }}
  idin_id: {{ .Values.security.idinId | b64enc | quote }}
  idin_secret: {{ .Values.security.idinSecret | b64enc | quote }}

